### ISSUE TITLE
Arreglar tests unitarios

### ISSUE THREAD

**Issue by mrivas10** [PepeCesarG/decide-full-alcazaba#109]
Sería conveniente la reparación de los tests unitarios, debido a que actualmente se detectan fallos en el código. Convendría, que esto funcionaran correctamente, para así automatizar las pruebas.

**Comment by antoniojss1** [comment]
He estado trabajando con otro compañero y he tenido que modificar mi entorno de trabajo y actualmente me funcionan los tests.
![Captura de pantalla de 2022-01-07 19-13-03](https://user-images.githubusercontent.com/72548940/148588137-4cee8a0b-0b77-4651-81f4-caea493a5045.png)
 Es cierto que antes me daban fallo pero de tiene que deber a que el entorno tiene incompatibilidades.
